### ISSUE TITLE
404

### ISSUE THREAD

**Issue by layladeliah** [Mabi19/stardew-perfection-randomizer#4]
For some reason I'm getting a 404 when trying to use this on my app or browser.

**Comment by Mabi19** [comment]
Can you elaborate? What page are you getting the 404? I was doing some stuff with migration recently, is it fixed now?

**Comment by layladeliah** [comment]
It seems to be fixed now and I migrated, so maybe it was just that. Sorry I wasn't too specific I wasn't sure what to say
