### ISSUE TITLE
Some fish goals not possible until fishing other fish

### ISSUE THREAD

**Issue by gnorfix** [Mabi19/stardew-perfection-randomizer#5]
Hey, so I've been doing the randomizer challenge and didn't know where else to put this comment, but I had my first  goal as catch a scorpion carp and got up to that point no problem, but when I was catching it, I couldn't get it, so I went to the internet and found this post: https://community.playstarbound.com/threads/sunfish-first-fish.142003/
At post number 8 a person called MouseyPonds explained that some fish do and some fish don't override the sunfish, so like half of the fish goals aren't fully achievable until you get the sunfish or any other from that list (don't know if it's up to date).
I don't know if you still update the picker, but if you do this can be something that can be looked into for better accuracy of the challenge.

**Comment by Mabi19** [comment]
I could probably implement that with the current template logic, though I'll ask Argon first. Thanks for reporting this by the way

**Comment by Mabi19** [comment]
UPDATE: The Sunfish override is actually avoidable! By catching a special item, like a Golden Walnut, you can add something to your fishing collection that is not a fish, and this bypasses the tutorial. I'm not going to close this as Won't Fix, though, as having a collection of tips like this would be good to have

**Comment by Mabi19** [comment]
Fishing tutorial bypassing got fixed in 1.6, and the Randomizer was adjusted for it.
